### ISSUE TITLE
Conditionals not evaluated properly

### ISSUE THREAD

**Issue by AlexanderStein** [robherring/dt-schema#13]
I'm currently trying to check on `meson-g12b-odroid-n2.dt` warnings and I noticed a warning regarding spicc* nodes about additional clock names. Although the condition check in `Documentation/devicetree/bindings/spi/amlogic,meson-gx-spicc.yaml` seems fine.
 When I remove `"plck"` from `spicc0` and run dt-validate manually and verbosely

> `dt-validate -u Documentation/devicetree/bindings -p build_meson/Documentation/devicetree/bindings/processed-schema.yaml build_meson/arch/arm64/boot/dts/amlogic/meson-g12b-odroid-n2.dt.yaml -v`

I get both warnings, that clock-names is too short as well it is too long:

```
> /home/alex/wine/repo/linux/build_meson/arch/arm64/boot/dts/amlogic/meson-g12b-odroid-n2.dt.yaml: spi@13000: clock-names: ['core'] is too short
> 
> Failed validating 'minItems' in schema['if']['then']['properties']['clock-names']:
>     {'additionalItems': False,
>      'items': [{'const': 'core'}, {'const': 'pclk'}],
>      'maxItems': 2,
>      'minItems': 2,
>      'type': 'array'}
> 
> On instance['clock-names']:
>     ['core']
> /home/alex/wine/repo/linux/build_meson/arch/arm64/boot/dts/amlogic/meson-g12b-odroid-n2.dt.yaml: spi@15000: clock-names: Additional items are not allowed ('pclk' was unexpected)
> 
> Failed validating 'additionalItems' in schema['properties']['clock-names']:
>     {'additionalItems': False,
>      'items': [{'const': 'core'}],
>      'maxItems': 1,
>      'minItems': 1,
>      'type': 'array'}
> 
> On instance['clock-names']:
>     ['core', 'pclk']
> /home/alex/wine/repo/linux/build_meson/arch/arm64/boot/dts/amlogic/meson-g12b-odroid-n2.dt.yaml: spi@15000: clock-names: ['core', 'pclk'] is too long
> 
> Failed validating 'maxItems' in schema['properties']['clock-names']:
>     {'additionalItems': False,
>      'items': [{'const': 'core'}],
>      'maxItems': 1,
>      'minItems': 1,
>      'type': 'array'}
> 
> On instance['clock-names']:
>     ['core', 'pclk']
```
Apparently the clock-names entries are both checked against the default ones (just "core") as well as the conditional ones ("core" and "pclk").
IMHO if the condition is fulfilled, the regular `schema['properties']['clock-names']` should be ignored.

**Comment by robherring** [comment]
While yes, it would be nice if there was a way to override schema, that's not the way json-schema and if/then schema works. The base schema has to validate all cases and then one or more if/then/else schemas can be more specific.

Also, please submit issues against devicetree-org/dt-schema rather than this one.
