### ISSUE TITLE
HTTPS support for references

### ISSUE THREAD

**Issue by aparcar** [robherring/dt-schema#21]
Currently it looks like only http references are supported, please allow HTTPS as well.
https://github.com/robherring/dt-schema/blob/d3f984f9233dc2db37bba3aecd3fb1c5be306912/dtschema/lib.py#L620

**Comment by robherring** [comment]
Should be easy enough, but you know that other than the spec schema, none of the devicetree.org schemas are live urls? Part of what the resolver does is re-write the URLs to local path(s).
